### ISSUE TITLE
Suggestion: Multithreading

### ISSUE THREAD

**Issue by xsmile** [InspectorMustache/maninex#1]
Thanks for providing a working solution to manage extensions.

You might want to implement multithreading to process multiple extensions simultaneously and speed up things a bit.

**Comment by RealFerdinandDeSaussure** [comment]
Ooops, sorry for the late reply. Never had a Github issue before, haha.

I think multithreading is a good idea and should be easy to do since there's no shared data between individual extensions. So this shouldn't take too long. The only reason I didn't implement this before is because I myself only have like 4 extensions to manage.

**Comment by RealFerdinandDeSaussure** [comment]
'Tis done.

**Comment by RealFerdinandDeSaussure** [comment]
Threading here is VERY basic but I think it should by all means be sufficient enough. I didn't implement an upper limit for concurrently running threads because I'm pretty sure no one out there has 6000 extensions installed. If anyone has, please open a new issue.
